### ISSUE TITLE
Syntax/highlighting/autoformat errors and feature requests

### ISSUE THREAD

**Issue by j-danner** [abacus42/CoCoA-Vim#2]
##### add highlighting for:
- function-names which include numbers
- the keywords '_isin_', '_IsIn_', '_and_', and '_or_'

##### fix highlighting for:
- '_zero()_', '_one()_', and '_IsZero()_' which is for some reason not correct (at least with my setup....)

##### fix autoformat for:
- _if_, _else_, _endif_ in the case that _endif_ is too far indented
- in the case that one forgets '_then_', indentation is often incorrect (for instance when using 'elif')
--> should we ignore this case since it is invalid syntax?

##### suggestions for new features
- add match support to quickly jump from '_define_' to '_enddefine_' (and vice versa) using `%`
- add support to jump to definition of a function (if it is in the same file), i.e. when the cursor is over _foo(args)_ then pressing `f` jumps to the first occurrence of 'define foo' in the same file

**Comment by abacus42** [comment]
> ##### add highlighting for:
> 
>     * function-names which include numbers
> 
>     * the keywords '_isin_', '_IsIn_', '_and_', and '_or_'

Highlighting for functions that include numbers after the first position has been added.
The highlighting of the keywords seems to be a theme specific problem.

> ##### fix highlighting for:
> 
>     * '_zero()_', '_one()_', and '_IsZero()_' which is for some reason not correct (at least with my setup....)

I removed these keywords since they are highlighted as functions anyway. This should also fix your problem.

> ##### fix autoformat for:
> 
>     * _if_, _else_, _endif_ in the case that _endif_ is too far indented
> 
>     * in the case that one forgets '_then_', indentation is often incorrect (for instance when using 'elif')
>       --> should we ignore this case since it is invalid syntax?

Yes, I would suggest to ignore indentation problems caused by incorrect syntax.

> ##### suggestions for new features
> 
>     * add match support to quickly jump from '_define_' to '_enddefine_' (and vice versa) using `%`
> 
>     * add support to jump to definition of a function (if it is in the same file), i.e. when the cursor is over _foo(args)_ then pressing `f` jumps to the first occurrence of 'define foo' in the same file

Support for matchit and matchup has been added.
